#!/usr/bin/env python3

# ===============================================================================
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
# ===============================================================================


def Fib():
    a, b = 0, 1
    yield a
    yield b
    while True:
        a, b = b, a + b
        yield b


def solution():
    n = Fib()
    summ = 0
    for i in n:
        if i < 4e6:
            if i % 2 == 0:
                summ += i
        else:
            break
    return summ


if __name__ == '__main__':
    print(solution())
