#!/usr/bin/env python3

# ===============================================================================
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
# Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
# Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
# ===============================================================================


def T():
    n = 285
    while True:
        yield int(n * (n + 1) / 2)
        n += 1


def P():
    n = 165
    while True:
        yield int(n * (3 * n - 1) / 2)
        n += 1


def H():
    n = 143
    while True:
        yield int(n * (2 * n - 1))
        n += 1


def solution():
    tg, pg, hg = T(), P(), H()
    t = set()
    p = set()
    h = set()
    for i in range(100000):
        t.add(next(tg))
        p.add(next(pg))
        h.add(next(hg))
    print((t & p) & h)


if __name__ == '__main__':
    print(solution())
